module.exports = {
  ANSWERS_RECEIVED: "ANSWERS_RECEIVED",
  ANSWER_RECEIVED: "ANSWER_RECEIVED",
  ANSWER_DELETED: "ANSWER_DELETED",
  ANSWER_EDITED: "ANSWER_EDITED",
	VOTE_REMOVED: 'VOTE_REMOVED',
	VOTE_ADDED: 'VOTE_ADDED'
};
